# Site update
repository: jeenikanadani/resume
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Jeenika R. Anadani
title: Security Consultant
email: jeenikanadani26@gmail.com
# email_title: Email (Email title override)
# phone: Your phone number (optional)
# phone_title: Phone (Phone title override)
website: https://jeenika.com
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: j33n1k4
github_username:  jeenikanadani
linkedin_username: jeenika
# facebook_username: jekyll
# instagram_username: jekyll
# youtube_username: jekyll


# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
 A cyber security enthusiast with 2 Years of working experience in Vulnerability Assessment, Vulnerability Management, Penetration Testing. I also have a Bachelor’s Degree in Computer Science & Engineering Shivaji University and a Diploma Degree in Computer Science & Engineering Shivaji University. I sometimes play CTF’s on hackthebox, lab.pentestit.ru, root-me.org, overthewire, tryhackme and others. I also document my learnings which can be found on my blog. I'm self-confident, self-Learner, fluent speaker, funny and naturally passionate in Information Security.

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content: 
      - layout: top-middle
        border: weak
        title: Nuclei Template
        link_text: Nuclei Configuration Listing Template
        link: https://github.com/projectdiscovery/nuclei-templates/blob/master/exposures/configs/configuration-listing.yaml
        additional_links:
          - title: Nuclei (Project Discovery)
            icon: fab fa-github
            url: https://github.com/projectdiscovery/nuclei-templates/blob/master/exposures/configs/configuration-listing.yaml
      - layout: top-middle
        title: Rooting the Android Studio AVDs
        link_text: Android Studio AVD Root
        link: https://github.com/jeenikanadani/android-studio-avd-root
        additional_links:
          - title: Rooting the Android Studio AVDs
            icon: fab fa-github
            url: https://github.com/jeenikanadani/android-studio-avd-root
  
  - title: Experience
    layout: list
    content:
    - layout: left
      title: Securelayer7
      sub_title: Associate Security Consultant
      caption: JULY 2019 TO PRESENT
      link_text: Securelayer7 Website
      link: https://securelayer7.net/
      quote: >
        Learnt and Performed Vulnerability Assessment & Penetration Testing on various softwares.
      description: |
        - Web and API Application Vulnerability Assessment & Penetration Testing.
        - Good Understanding on Docker and Docker-Composer.
        - Testing on REST and SOAP based API.
        - Mobile Applications Vulnerability Assessment & Pentration Testing (Android/IOS)
        - Network Vulnerability Assessment & Penetration Testing.
        - Thick Client Application Penetration Testing.
        - Cloud Security Testing.
        - Working on Kubernetes and other orchestration system.
        - Proactive Research on Latest Vulnerabilities and Exploits.
        - Identifying risks and mitigating controls.
        - Preparing reports documenting based on internal templates.
        - Testing and analysis of bench marking the application against industry standards such as OWASP, SANS, NIIST.
        - Performing Wireless Penetration Testing. 
        - Hardware Testing


  - title: Education
    layout: list
    content:
      - layout: left
        border: weak
        title: Sanjay Ghodawat Institues
        sub_title: BE. CSe
        caption: 2015 - 2019
        quote: >
          Bachelors of Engineering in Computer Science & Engineering (BE.CSE)
        description: |
          It all started with Fundamentals of Programming. I learnt a variety of programming languages. Over the period of my course, I was trained in C & C++, Java, SQL, ASPX, HTML. I learned about Data Structures, Object Oriented Programming, Operating Systems, Database Management Systems, Computer Networks, System Architecture, Software Engineering, Hadoop etc.
      - layout: left
        border: weak
        title: Dr. D. Y. Patil Polytechnic 
        sub_title: Diploma. CSe
        caption: 2012 - 2015
        quote: >
          Diploma in Computer Science & Engineering (DIP.CSE)
        description: |
          I learnt various Fundamentals of Computers and its Applications, Data Structures, Microproessor & Assembly Language Programming, Computer Networking, Database Management Systems, Real Time Operating Systems, Computer Organisation and Architecture & a lot of Mathematics - Probability, Fourier Transformations, Graph Theory, Boolean Algebra, Operations, etc. etc.

  - title: Certifications
    layout: list
    content:
      - layout: top-middle
        title: OSCP (Offensive Security Certified Professional)
        link_text: OSCP 
        link: https://www.credly.com/badges/bca51930-4b61-417f-bc09-25949e8af5eb/public_url
        

  - title: Presentations
    layout: list
    content:
      - layout: top-left
        border: weak
        title: Infosecgirls
        link_text: Infosecgirls Blog
        link: https://infosecgirls.in/blog/2020/02/29/2020-02-29-infosecgirls-pune-monthlymeet-2020/
        quote: >
          Local File Inclusion & Directory Traversal 
        description: |
          I presented a session about 2 of the web application attacks i.e Local File Inclusion & Directory Traversal and also hightlighted the main difference between Local File Inclusion & Directory Traversal by giving practical demonstration. I also spoke about impact of both the attacks
     
      - layout: top-left
        border: weak
        title: Null Ahmedabad
        link_text: Null Ahmedabad Youtube
        link: https://www.youtube.com/watch?v=AUUFfxXjxI4
        quote: >
          Let's Talk about OSCP and a career in Cyber Security
        description: |
          People who pentest towards offensive side definitely want to be a OSCP certified, but due to its toughness and challenging nature it gets confusing while preparing. In this talk, I spoke about who to prepare OSCP, key takeaways, important points & suggestions for praparation of OSCP exam. 
   
      - layout: top-left
        border: weak
        title: Disha Infosec
        link_text: Disha Infosec Youtube
        link: https://www.youtube.com/watch?v=SY2CcrzT5MU
        quote: >
          Social Engineering
        description: |
          I gave a webinar on Social Engineering wear I spoke about Different types on Social Engineering Attacks. Also gave a idea on what meassures to take if you're a victim & also how to look for red flags to avoid being a victim.

      - layout: top-left
        title: Securelayer7
        link_text: Securelayer7 Youtube
        link: https://www.youtube.com/watch?v=Fs_1gBuJS2M&t=81s
        quote: >
          CISO: Strategies of tomorrow's cybersecurity
        description: |
          I spoke about importance of Cyber Security with Business Perspective, how to identify areas of risks, understanding threats and risks, reliable cloud alternative. I also highlighted some important aspects such as importance of Encrypting the data, Use of strong passwords, Importance of Maintenance & Scheduling backups and also Educating / Training employees.

  - title: Skills
    layout: list
    content:
    - layout: left
      title: Programming Languages & Scripting
      description: | # this will include new lines to allow paragraphs
         - PHP
         - Bash

    - layout: left
      title: Operating Systems
      description: |
        - Linux
        - Windows
    
    - layout: left 
      title: Security Testing Method
      description: |
        - Black Box
        - White Box 
        - Grey Box 

    - layout: left 
      title: Tools
      description: |
        - Burpsuite
        - Nmap
        - Metasploit
        - Nessus 
        - Immunity Debugger
        - Acunetix
        - IDA Pro 
        - OpenVAS and other Penetration Testing Tool

    - layout: left 
      title: Security Testing Skills
      description: |
        - Manual Analysis
        - Exploitation
        - VAPT
        - Web Application Testing
        - Thick Client Application Security
        - API Testing
        - Mobile Application Testing
        - Docker & Kubernetes Testing
        - Hardware Testing
    




# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
